preseed: localization
- Time = Berlin
- Keyboard = DE
- Encoding = UTF-8

Use UTF-8 as that is required by Ansible, see:
ERROR: Ansible requires the locale encoding to be UTF-8; Detected ISO8859-1.